version: '3'

services:
  # Spring Boot Application
  d2c-payment-service:
    image: gradle:8.10-jdk17  # Gradle image with Java 17
    container_name: d2c-payment-service-app
    working_dir: /app
    volumes:
      - .:/app               # Mount project root into container
    ports:
      - "9082:9082"          # Expose port 8080 for Spring Boot
    command: ./gradlew bootRun  # Command to run the Spring Boot app
    stdin_open: true
    tty: true
    networks:
      - my_shared_network
    environment:
      - SERVICE_NAME=d2c-payment-service

  prometheus:
    image: prom/prometheus
#    restart: unless-stopped
    container_name: prometheus
    network_mode: "host" # Published ports are discarded when using host network mode
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    extends:
      file: docker-compose-grafana.yml
      service: grafana

networks:
  my_shared_network:
    driver: bridge
    
#networks:
 # my_shared_network:
  #  external: true
